# NumPy

## 1. Given a space-separated list of integers, convert it into a NumPy array.0

In [1]:
import numpy as np

In [12]:
list_1="10 20 30 40 50"
splited_numbers=list_1.split()
s=list(map(int,splited_numbers))
arr1=np.array(s)
print(arr1)

[10 20 30 40 50]


In [13]:
arr1.ndim

1

## 2. Create a 3x3 NumPy array from a list of 9 integers.

In [17]:
list_2=[1,2,3,4,5,6,7,8,9]
arr=np.array(list_2).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
arr.ndim

2

## 3. Given two 2D square matrices, compute their dot product and cross product using NumPy.


In [38]:
A=np.array([[1,2],[4,5]])
B=np.array([[7,8],[10,11]])
dot_product=np.dot(A,B)
print(dot_product)


[[27 30]
 [78 87]]


In [39]:
print(B)
B.ndim

[[ 7  8]
 [10 11]]


2

* Cross product only works for 1D and 3D vector
* There is no general mathematical definition of cross product for 2D matrices.

## 4. Find the minimum value of each row and then the maximum of those minimums.

In [44]:
arr_3D = np.array([
    [[1,2,3],[6,7,8,],[11,12,13]]
])
row_min=np.min(arr_3D,axis=1)# finding the minimum across the columns hence axis=1
print(row_min)
Max_of_min=np.max(row_min)
print(Max_of_min)

[[1 2 3]]
3
