In [12]:
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import numpy as np

In [3]:
movie_df=pd.read_csv("Movies_dataset.csv")

In [4]:
movie_df

Movie Title  Ratinng                     genre   
0             3 Idiots      8.4             Comedy, Drama  \
1     Taare Zameen Par      8.3             Drama, Family   
2                   PK      8.1     Comedy, Drama, Sci-Fi   
3               Dangal      8.3  Action, Biography, Drama   
4      Rang De Basanti      8.1      Comedy, Crime, Drama   
..                 ...      ...                       ...   
806   Parde Ke Peechey      5.9                    Action   
807            Dhamkee      4.0            Action, Comedy   
808       Chhoo Mantar      6.0                    Comedy   
809  Ladki Sahyadri Ki      5.0            Musical, Drama   
810          Madadgaar      7.2            Drama, Romance   

                                                   act   
0    Aamir Khan, Madhavan, Mona Singh, Sharman Josh...  \
1    Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...   
2    Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...   
3    Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...   
4    Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...   
..                                                 ...   
806  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...   
807  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...   
808  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...   
809  Shalini Abhyankar, Keshavrao Date, Vatsala Des...   
810  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...   

                                                  Plot  
0    papadum, hairy chest, against the system, comi...  
1    teacher student relationship, dyslexia, agains...  
2    guru, religion, tv reporter, alien on earth, p...  
3    small town, father daughter relationship, male...  
4    delhi india, murder, friend, india, awakening,...  
..                                                 ...  
806                                              crook  
807                                              sorry  
808  rescue, beating, river, village, wedding, flir...  
809                                              sorry  
810                                              sorry  

[811 rows x 5 columns]

In [5]:
movie_df.isna().sum()

Movie Title    0
Ratinng        0
genre          0
act            0
Plot           0
dtype: int64

In [6]:
movie_df.dtypes

Movie Title     object
Ratinng        float64
genre           object
act             object
Plot            object
dtype: object

In [8]:
tfidf=TfidfVectorizer()

In [9]:
Vectors=tfidf.fit_transform(movie_df["genre"])

In [13]:
Vectors[2].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23854688,
        0.        , 0.        , 0.15553797, 0.        , 0.        ,
        0.67782864, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.67782864, 0.        , 0.        ,
        0.        , 0.        ]])

In [14]:
Vectors[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.83766858,
        0.        , 0.        , 0.54617887, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [15]:
Vectors[100].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.83766858,
        0.        , 0.        , 0.54617887, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [17]:
indexed=pd.Series(index=movie_df["Movie Title"],data=movie_df.index)

In [18]:
indexed

Movie Title
3 Idiots               0
Taare Zameen Par       1
PK                     2
Dangal                 3
Rang De Basanti        4
                    ... 
Parde Ke Peechey     806
Dhamkee              807
Chhoo Mantar         808
Ladki Sahyadri Ki    809
Madadgaar            810
Length: 811, dtype: int64

In [19]:
indexed["PK"]

2

In [22]:
dis=linear_kernel(Vectors[0],Vectors)

In [23]:
dis

array([[1.        , 0.17682135, 0.28477478, 0.14539681, 0.68713209,
        0.27882285, 0.44125755, 0.10959635, 1.        , 0.34989062,
        0.73593791, 0.56163239, 0.27882285, 0.56163239, 0.16734622,
        0.10505635, 0.        , 0.28702413, 0.13272403, 0.54617887,
        0.        , 0.20462232, 0.17394914, 0.46705206, 0.13318935,
        0.34989062, 0.56163239, 0.27882285, 0.73593791, 0.48782829,
        0.16384446, 0.44035717, 0.18746835, 0.20462232, 0.56396402,
        0.        , 0.76492377, 0.13272403, 0.16384446, 0.27882285,
        0.53090047, 0.        , 0.        , 0.76492377, 0.10505635,
        0.13272403, 0.13272403, 0.27882285, 0.        , 0.15563719,
        0.44125755, 1.        , 0.73593791, 0.16384446, 0.44125755,
        0.27882285, 0.11589395, 0.13095659, 0.1575185 , 0.25066587,
        0.18746835, 0.20462232, 0.12955874, 1.        , 0.21910022,
        0.17394914, 0.53090047, 0.21910022, 0.18746835, 0.73593791,
        0.20462232, 0.54617887, 0.73593791, 0.  

In [26]:
scores=pd.DataFrame(dis).T

In [33]:
scores.columns=["score"]

In [35]:
x=scores.sort_values("score",ascending=False)

In [48]:
x

score
0      1.0
261    1.0
100    1.0
755    1.0
241    1.0
..     ...
73     0.0
316    0.0
708    0.0
642    0.0
550    0.0

[811 rows x 1 columns]

In [52]:
movie_df

Movie Title  Ratinng                     genre                                                act                                               Plot
0             3 Idiots      8.4             Comedy, Drama  Aamir Khan, Madhavan, Mona Singh, Sharman Josh...  papadum, hairy chest, against the system, comi...
1     Taare Zameen Par      8.3             Drama, Family  Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...  teacher student relationship, dyslexia, agains...
2                   PK      8.1     Comedy, Drama, Sci-Fi  Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...  guru, religion, tv reporter, alien on earth, p...
3               Dangal      8.3  Action, Biography, Drama  Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...  small town, father daughter relationship, male...
4      Rang De Basanti      8.1      Comedy, Crime, Drama  Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...  delhi india, murder, friend, india, awakening,...
..                 ...      ...                       ...                                                ...                                                ...
806   Parde Ke Peechey      5.9                    Action  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...                                              crook
807            Dhamkee      4.0            Action, Comedy  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...                                              sorry
808       Chhoo Mantar      6.0                    Comedy  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...  rescue, beating, river, village, wedding, flir...
809  Ladki Sahyadri Ki      5.0            Musical, Drama  Shalini Abhyankar, Keshavrao Date, Vatsala Des...                                              sorry
810          Madadgaar      7.2            Drama, Romance  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...                                              sorry

[811 rows x 5 columns]

In [43]:
movie_df

Movie Title  Ratinng                     genre                                                act                                               Plot
0             3 Idiots      8.4             Comedy, Drama  Aamir Khan, Madhavan, Mona Singh, Sharman Josh...  papadum, hairy chest, against the system, comi...
1     Taare Zameen Par      8.3             Drama, Family  Darsheel Safary, Aamir Khan, Tisca Chopra, Vip...  teacher student relationship, dyslexia, agains...
2                   PK      8.1     Comedy, Drama, Sci-Fi  Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...  guru, religion, tv reporter, alien on earth, p...
3               Dangal      8.3  Action, Biography, Drama  Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...  small town, father daughter relationship, male...
4      Rang De Basanti      8.1      Comedy, Crime, Drama  Aamir Khan, Soha Ali Khan, Siddharth, Sharman ...  delhi india, murder, friend, india, awakening,...
..                 ...      ...                       ...                                                ...                                                ...
806   Parde Ke Peechey      5.9                    Action  Vinod Mehra, Yogeeta Bali, Pran Sikand, Bindu ...                                              crook
807            Dhamkee      4.0            Action, Comedy  Ravi Teja, Anushka Shetty, Krishna, Pradeep Si...                                              sorry
808       Chhoo Mantar      6.0                    Comedy  Shyama, Johnny Walker, Anita Guha, Gajanan Jag...  rescue, beating, river, village, wedding, flir...
809  Ladki Sahyadri Ki      5.0            Musical, Drama  Shalini Abhyankar, Keshavrao Date, Vatsala Des...                                              sorry
810          Madadgaar      7.2            Drama, Romance  Ravindra Kapoor, Indira, Jeevan Dhar, Uma Dutt...                                              sorry

[811 rows x 5 columns]

In [53]:
indexed[indexed==261]


Movie Title
Malamaal Weekly    261
dtype: int64